### ISSUE TITLE
undefined parameters; please review code and reply

### ISSUE THREAD

**Issue by nazneenshaikh-db** [AhmedSarhan/react-hook-form#2]
![one](https://user-images.githubusercontent.com/55677796/118522088-897cdd00-b6f0-11eb-934f-87a66350b239.jpg)
![two](https://user-images.githubusercontent.com/55677796/118522106-8eda2780-b6f0-11eb-8cde-d9e9255577fb.jpg)
![three](https://user-images.githubusercontent.com/55677796/118522119-926dae80-b6f0-11eb-80cb-a072918ca10d.jpg)
![four](https://user-images.githubusercontent.com/55677796/118522129-96013580-b6f0-11eb-82b3-913167287ad8.jpg)
![five](https://user-images.githubusercontent.com/55677796/118522148-9994bc80-b6f0-11eb-944e-36518f9b3380.jpg)

**Comment by nazneenshaikh-db** [comment]
Commented the same issue on your yt channel

**Comment by AhmedSarhan** [comment]
![code-snapshot](https://user-images.githubusercontent.com/20737908/118537459-400eab00-b74d-11eb-906e-1c587b1ffc9b.png)
I believe things got mixed up with you in the function name and data coming from the inputs 
please refer to this video as well [third video in the playlist](https://youtu.be/b347AJfOXgI?list=PLFh6HAUiGt6GrO1jJhe-y0r7O_mtM_02N)

**Comment by AhmedSarhan** [comment]
solved
